---
title: "Exam1"
author: "Beatrice Severance, Zachary Noel"
date: "2023-03-03"
output: 
  html_document: 
    keep_md: yes
    word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

### Question 4
```{r}
#load in and view dataset
data("PlantGrowth")
head(PlantGrowth)

#load dependencies
library(ggplot2)

#layering
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_point(aes(color = group))

#scales
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_point(aes(color = group)) +
  theme_classic() +
  facet_wrap(~group, scales = "free")

#theme
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_point(aes(color = group)) +
  theme_classic()

ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_point(aes(color = group)) +
  theme_bw()

#facets
ggplot(PlantGrowth, aes(x = group, y = weight)) +
  geom_point(aes(color = group)) +
  theme_classic() +
  facet_wrap(~group, scales = "free_x")
```

### Question 5
```{r}
#load in and view dataset
data("ToothGrowth")
head(ToothGrowth)

#two ways to subset supp = VC
tooth.supp.eq.vc <- ToothGrowth[ToothGrowth$supp == "VC",]
tooth.supp.eq.vc1 <- subset(ToothGrowth, supp == "VC")

#two ways to subset supp = VC and dose = 0.5
tooth.suppvc.dose05 <- ToothGrowth[ToothGrowth$supp == "VC" & 
                                     ToothGrowth$dose == 0.5,]
tooth.suppvc.dose05.1 <- subset(ToothGrowth, supp == "VC" & dose == 0.5)

#two ways to display len values when supp = VC and dose = 0.5
tooth.supp.len <- tooth.suppvc.dose05$len
print(tooth.supp.len)
tooth.supp.len1 <- tooth.suppvc.dose05.1[ , 1]
print(tooth.supp.len1)
```